theme: jekyll-theme-minimal  # Change theme if needed
title: My Personal Website  # Change this to your desired title
description: Welcome to my website! Stay updated on my projects.  # Add a description
